---
- set_fact:
    ansible_user: pentest
    ansible_ssh_user: pentest
    remote_user: pentest

- name: Install necessary gem bundler
  become: true
  shell: bash -cl "gem install bundler -f"

- name: Install necessary gem wirble
  become: true
  shell: bash -cl "gem install wirble -f"

- name: Install necessary gem sqlite3
  become: true
  shell: bash -cl "gem install sqlite3 -f"

- name: Apt install metasploit deps
  become: true
  apt:
    name: "{{ item }}"
    state: present
    update_cache: yes
    cache_valid_time: 3600
  loop:
    - gpgv2
    - autoconf
    - bison
    - build-essential
    - curl
    - git-core
    - libapr1
    - libaprutil1
    - libcurl4-openssl-dev
    - libgmp3-dev
    - libpcap-dev
    - libpq-dev
    - libreadline6-dev
    - libsqlite3-dev
    - libssl-dev
    - libsvn1
    - libtool
    - libxml2
    - libxml2-dev
    - libxslt-dev
    - libyaml-dev
    - locate
    - ncurses-dev
    - openssl
    - postgresql
    - postgresql-contrib
    - wget
    - xsel
    - zlib1g
    - zlib1g-dev

- name: Mkdir msf directory
  file:
    state: directory
    path: "/home/pentest/msf"

- name: Git checkout metasploit source
  become_user: "pentest"
  git:
    repo: https://github.com/rapid7/metasploit-framework.git
    dest: "/home/pentest/msf"
    update: no

- name: Make sure no Gemfile.lock is present
  become: true
  file:
    path: "{{ item }}"
    state: absent
  loop:
    - /home/pentest/msf/Gemfile.lock

- name: Run bundle install
  # become_user: "pentest"
  become: true
  shell: chdir=/home/pentest/msf bash -cl "bundle install"
